# Generated by Django 4.0.3 on 2022-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0004_remove_super_primary_ability_super_primary_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='primary_ability',
        ),
        migrations.AddField(
            model_name='super',
            name='primary_ability',
            field=models.ManyToManyField(to='supers.power'),
        ),
    ]
